name: Auto-merge Dependabot PRs

on:
  pull_request:

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: dependabot-auto-merge-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  auto-merge:
    if: github.actor == 'dependabot[bot]'
    uses: benhigham/.github/.github/workflows/auto-merge-dependabot.yml@7a1eb9105ae462853ee01a41ad45518b4bae51c9
